### ISSUE TITLE
Day 03 - EC2 Instance

### ISSUE THREAD

**Issue by ironpeak** [hgop/syllabus-2021#10]
Each group should leave comment here:

~~~
Team Name: dreamteam
Repository: your-private-github-repository
~~~

Where the Team Name is something unique (hasn't been commented before).
* We'll setup an EC2 instance on AWS for you that you will install microk8s on.
* We'll setup a CNAME record for dns so that team-name.hgopteam.com will point to your ec2 instance.

We will put a thumbs up on your comment once its done. Make sure you've added @ironpeak and @kthorri to your project repository, so we can share the instance key with you.

**Your instance key is private, it should not be shared outside your team.**

**Comment by ironpeak** [comment]
~~~
Team Name: dreamteam
Repository: https://github.com/ironpeak/hgop-2021
~~~

**Comment by steinzi** [comment]
Team Name: noiinteam
Repository: https://github.com/steinzi/hgop

**Comment by MyraMidnight** [comment]
Team name: Grísanaggar
repository: https://github.com/MyraMidnight/hgop-2021-h3

**Comment by Valtyrs** [comment]
Team name: veryEpicTeamName
Repository: https://github.com/Valtyrs/HGOP

**Comment by bjorgvin92** [comment]
Team name: Prinsessurnar
Repository: https://github.com/bjorgvin92/HGOP_7

**Comment by IngaI** [comment]
Team Name: ThreesCompany
Repo: https://github.com/IngaI/hgop_2021

**Comment by Arnarps** [comment]
Team name: ThunderDucks
Repo: [https://github.com/Arnarps/HGOP]

**Comment by OliBirgir** [comment]
Team name: Krumpaðir
Repo: https://github.com/OliBirgir/HGOP-Group4

**Comment by jonakaren** [comment]
Team name: Bjóna
Repo: https://github.com/bjorgvin16/HGOP-group-1

**Comment by Ramruqai** [comment]
Team name: asgeir09
Repo: https://github.com/Ramruqai/hgopasgeir09

**Comment by robertatli** [comment]
Team name: publicSymbol
Repo: https://github.com/danielagustbjornsson/T-542-HGOP

**Comment by adambjorgvins** [comment]
Team name: adamb18
Repo: https://github.com/adambjorgvins/hgop
