### ISSUE TITLE
Vesen með Dockerfile

### ISSUE THREAD

**Issue by OliBirgir** [hgop/syllabus-2021#16]
RUN commandið hjá okkur virðist ekki virka.
RUN command -> RUN yarn build
ERROR -> "Failed to Load SWC binary"

**Comment by kthorri** [comment]
Getur þú paste'að Dockerfile línurnar þangað til yarn build línan er keyrð?

**Comment by OliBirgir** [comment]
<img width="386" alt="Screenshot 2021-11-23 at 22 02 22" src="https://user-images.githubusercontent.com/54917165/143136310-9bb6a871-e63c-474c-baea-b3c2a4988b30.png">

**Comment by Arnarps** [comment]
Ég veit ekki nógu mikið um þetta hvort þetta syntax sem er virki en svona lítur mitt yarn copy út.
![image](https://user-images.githubusercontent.com/54935919/143212036-76f1ee31-7ec4-487e-92ec-e7f692d455a2.png)

það vantar þarf líka þessa files -> .yarnrc.yml .pnp.cjs .pnp.loader.mjs

ættir líklegast svo að bæta við einu skrefi áður en þú copyar allt yfir eftir COPY .yarn

**Comment by kthorri** [comment]
Ég held við séum með nóg til að loka þessu issue. @OliBirgir er amk kominn með Dockerfile sem virkar
