### ISSUE TITLE
503 service temporarily unavailable

### ISSUE THREAD

**Issue by jonakaren** [hgop/syllabus-2021#18]
Hefur einhver lent í því að fá þetta upp?
Þetta gerist þegar við reynum að opna connect4 síðuna.
Erum með connect4 á port 8001 og targetport 81 og httpbin á öðru.

<img width="1059" alt="Screenshot 2021-11-24 at 17 31 26" src="https://user-images.githubusercontent.com/70695859/143287153-633211cf-44c7-43d1-9ba0-97944c98212b.png">

**Comment by ironpeak** [comment]
target port fyrir connect4 ætti að vera 3000 ef þið breyttuð engu í NextJS.

Þetta er smá flókið, en það eru nokkur port mapping abstractions í gangi í kubernetes.

Ef við tökum httpbin sem var gefið sem dæmi:
Fyrsta er 443/80 sem lendir á nginx, sem notar les configuration-ið í ingressinu um að það eigi að senda traffic á port 8000, sem er abstraction fyrir service-ið sem mappar porti 8000 yfir í 80 svo traffic-in lendir á httpbin container-num á porti 80.\
Þetta virkar fyrir httpbin því hann er að hlusta á porti 80.

NextJS er hinsvegar að hlusta á porti 3000 svo það þarf að gera samsvarandi breytingar :)

**Comment by jonakaren** [comment]
Við erum búin að setja target port á 3000 en við erum ennþá óviss með portið, erum búin að prófa hitt og þetta en ekkert virkar ennþá.

**Comment by ironpeak** [comment]
ingress-port: X
service-target-port: X
service-targetPort: 3000
deployment-containerPort: 3000

X getur verið hvaða port sem er svo lengi sem það er það sama á báðum stöðum. X getur líka verið það sama fyrir bæði httpbin og connect4 án þess að valda neinu collision.

**Comment by ironpeak** [comment]
Ertu pods running?
`kubectl get pods`

**Comment by jonakaren** [comment]
Föttuðum að okkur vantaði taggið á image-ið okkar í deployment.yaml, virkar núna. Takk fyrir hjálpina
