### ISSUE TITLE
Certificate never becoming READY

### ISSUE THREAD

**Issue by hauks96** [hgop/syllabus-2021#19]
After creating our certificates we are unable to get them to become READY, what should we do? Both clients are running successfully.

```
NAME           READY   SECRET         AGE
connect4-tls   False   connect4-tls   85m
httpbin-tls    False   httpbin-tls    2m20s
```

**Comment by ironpeak** [comment]
Hvað kemur úr:
~~~bash
kubectl describe certificate connect4-tls
~~~

**Comment by IngaI** [comment]
~$ kubectl describe certificate connect4-tls

Name:         connect4-tls
Namespace:    default
Labels:       app=connect4
Annotations:  <none>
API Version:  cert-manager.io/v1
Kind:         Certificate
Metadata:
  Creation Timestamp:  2021-11-24T16:58:07Z
  Generation:          1
  Managed Fields:
    API Version:  cert-manager.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .:
          f:app:
        f:ownerReferences:
          .:
          k:{"uid":"c4a0eedc-0c40-4bcd-b465-39a2a8153f0c"}:
            .:
            f:apiVersion:
            f:blockOwnerDeletion:
            f:controller:
            f:kind:
            f:name:
            f:uid:
      f:spec:
        .:
        f:dnsNames:
        f:issuerRef:
          .:
          f:group:
          f:kind:
          f:name:
        f:secretName:
        f:usages:
      f:status:
        .:
        f:conditions:
        f:nextPrivateKeySecretName:
    Manager:    controller
    Operation:  Update
    Time:       2021-11-24T16:58:08Z
  Owner References:
    API Version:           networking.k8s.io/v1
    Block Owner Deletion:  true
    Controller:            true
    Kind:                  Ingress
    Name:                  connect4
    UID:                   c4a0eedc-0c40-4bcd-b465-39a2a8153f0c
  Resource Version:        25862
  Self Link:               /apis/cert-manager.io/v1/namespaces/default/certificates/connect4-tls
  UID:                     81112e4c-8f62-4c9a-8cfa-b7d623c64465
Spec:
  Dns Names:
    connect4.threescompany.hgopteam.com
  Issuer Ref:
    Group:      cert-manager.io
    Kind:       ClusterIssuer
    Name:       letsencrypt
  Secret Name:  connect4-tls
  Usages:
    digital signature
    key encipherment
Status:
  Conditions:
    Last Transition Time:        2021-11-24T16:58:08Z
    Message:                     Issuing certificate as Secret does not exist
    Observed Generation:         1
    Reason:                      DoesNotExist
    Status:                      False
    Type:                        Ready
    Last Transition Time:        2021-11-24T16:58:08Z
    Message:                     Issuing certificate as Secret does not exist
    Observed Generation:         1
    Reason:                      DoesNotExist
    Status:                      True
    Type:                        Issuing
  Next Private Key Secret Name:  connect4-tls-2bjbd
Events:                          <none>

og yaml skrárnar okkar eru svona:
![image](https://user-images.githubusercontent.com/54936567/143416075-5cf0f35c-b910-4759-ad2e-68bd59de2afd.png)

**Comment by ironpeak** [comment]
prófaðu að henda út ingress, service og deployment fyrir httpbin og connect4 og búa það svo til aftur.

**Comment by IngaI** [comment]
WhoopWhoop!
![image](https://user-images.githubusercontent.com/54936567/143459559-7ac9a94b-d1e9-43ee-89ec-7d9dbc2a7f2f.png)
