### ISSUE TITLE
Building docker in CircleCi

### ISSUE THREAD

**Issue by Ramruqai** [hgop/syllabus-2021#23]
Getting this bit of error when trying to building the docker in CircleCi. I've tried messing with the dockerfile it self (it works locally).
Google seems to suggest that changing the version of setup_remote_docker was the solution for most ppl that ran into something similar but has not done the trick for me (tried a few different versions).

`[3/4] Linking dependencies...
error An unexpected error occurred: "EPERM: operation not permitted, copyfile '/usr/local/share/.cache/yarn/v6/npm-caniuse-lite-1.0.30001283-8573685bdae4d733ef18f78d44ba0ca5fe9e896b-integrity/node_modules/caniuse-lite/LICENSE' -> '/app/node_modules/caniuse-lite/LICENSE'".
info If you think this is a bug, please open a bug report with the information provided in "/app/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
The command '/bin/sh -c yarn install' returned a non-zero code: 1

Exited with code exit status 1

`

Current build bit:
`build:
    docker:
    - image: cimg/base:stable
    steps:
    - checkout
    - setup_remote_docker:
        verison: 20.10.2
    - run:
        name: Build Docker image
        command: 
          docker build -t connect4-client ./src/connect4-client`

**Comment by ironpeak** [comment]
While waiting for the practical session, you can try creating a new branch and test generating NextJS app again.

**Comment by ironpeak** [comment]
Try recreating your docker file, took a look and it's a bit off:

~~~Dockerfile
# First we want to build on an image the includes the environment we need to build and run our code, we can use 'node:alpine':
TODO

# Now set the working directory to /app:
TODO

# Let's make sure all our dependencies are available
# copy package.json, yarn.lock and the .yarn directory into the current working directory:
TODO

# Now we need the rest of our application code, copy your entire folder into the image working directory:
# You should also create a .dockerignore file to improve build performance and keep unwanted files out of your container.
TODO

# Now we want to build our application code. HINT: To run package.json scripts, we can use `yarn {script}`
TODO

# Lastly we need to run the application when the container starts, set the command as yarn start:
TODO
~~~

**Comment by Ramruqai** [comment]
Prufaði báða þessa hluti. Einhver frekari hint hvað sé rang í docker?
Hvaða branch skoðaðiru?

**Comment by ironpeak** [comment]
Varstu búinn að fylgja:
https://yarnpkg.com/getting-started/migration#switching-to-plugnplay

**Comment by Ramruqai** [comment]
Já held það.
var það eitthvað meira en fjarlægja eina línu úr .yarnrc.yml og gera aftur yarn install?

**Comment by Ramruqai** [comment]
/home/asgeir/Pictures/Screenshot from 2021-11-26 11-35-52.png

Fun times error. :\

**Comment by Ramruqai** [comment]
![Screenshot from 2021-11-26 11-35-52](https://user-images.githubusercontent.com/54935678/143575182-9caeaa86-0e71-4da4-82b8-3975b9d0d811.png)

Fun times error

**Comment by Ramruqai** [comment]
To keep with tradition this of answering your own question when you find the solution.

The problem here was I was not pusing everything frm the .yarn folder due to wrong settings in gitignore. 

We are using the no-installs version of the gitignore suggested in assignment description if anyone cares to know.

**Comment by kthorri** [comment]
I take it that you found a solution to your problem, closing this, feel free to open again if not solved
