### ISSUE TITLE
Day04 Deploying to kubernetes

### ISSUE THREAD

**Issue by bjorgvin92** [hgop/syllabus-2021#24]
Trying to deploy to kubernetes.

Fails on "Install kubeconfig":
```
#!/bin/bash -eo pipefail
if [ -n "${KUBECONFIG_DATA}" ]; then
  mkdir -p $HOME/.kube
  echo -n "${KUBECONFIG_DATA}" | base64 --decode > $HOME/.kube/config
fi

base64: invalid input

Exited with code exit status 1

CircleCI received exit code 1
```

Ive set the environment variable:
![image](https://user-images.githubusercontent.com/42970144/143508475-456c5339-aae7-450a-a820-69493c115cf5.png)
And Ive decoded the same string myself and gotten what seems to be my exact kube config locally so it should be a valid base64 string.

**Comment by elisaeik** [comment]
Við erum að lenda í einmitt sama vandamálinu.

**Comment by hauks96** [comment]
**SAME HERE!** >O

**Comment by ironpeak** [comment]
Passaðu að það séu engin newline í base64 encoded string-num, stundum er þetta encoded:
~~~
XXXX
XXXX
XXXX
~~~
En ætti að vera:
~~~
XXXXXXXXXXXX
~~~

**Comment by bjorgvin92** [comment]
> Passaðu að það séu engin newline í base64 encoded string-num, stundum er þetta encoded:
> 
> ```
> XXXX
> XXXX
> XXXX
> ```
> 
> En ætti að vera:
> 
> ```
> XXXXXXXXXXXX
> ```

Takk takk, þetta reddaði málunum. Var alveg viss um að ég var að gera rétt vegna þess að online decoderinn var að gefa mér rétt output, greinilega var hann að cutta newlines út fyrir mig/hunsa þau.

**Comment by IngaI** [comment]
@bjorgvin92 náðir þú að klára deployment eða fékkstu aðra villu þegar þessi leystist?

**Comment by bjorgvin92** [comment]
> @bjorgvin92 náðir þú að klára deployment eða fékkstu aðra villu þegar þessi leystist?

Fékk aðra villu en fixxið var einfalt, gleymdi að gera merge scriptinuna execute-able(chmod -x)
