### ISSUE TITLE
How precise is the tree in day5?

### ISSUE THREAD

**Issue by IngaI** [hgop/syllabus-2021#27]
Wondering if our repository tree should look identical to the one in the instructions or if it is just a guideline?

![image](https://user-images.githubusercontent.com/54936567/143592692-0a20c5cb-4fa4-4b59-8d56-7a7b36d6743b.png)

**Comment by ironpeak** [comment]
Taktu út kubectl og kubectl.sha256 og búðu til pull request fyrir að breyta trénu í dag 5 og færð þá bonus fyrir vikuna :)
