### ISSUE TITLE
Release videos / syllabus for week 2?

### ISSUE THREAD

**Issue by IngaI** [hgop/syllabus-2021#29]
Even though we're not meant to work through the weekend it would be nice to know what to prepare for :)

**Comment by ironpeak** [comment]
Might be good to take a look at the lectures for next week since the practical part will be heavy.

Next week we'll be using python a lot as well, so you can brush up on that as well.

**Comment by IngaI** [comment]
@ironpeak the issue is that there are no lectures available for next week on Canvas.  It would be great if you could release them so we can prepare for next week and have more time for practical stuff.  The 1st week's lectures were almost 7 hours.
![image](https://user-images.githubusercontent.com/54936567/143656331-f09ce59f-3c07-447a-8cc2-66359fa0f239.png)
