### ISSUE TITLE
Deploying (secret related)

### ISSUE THREAD

**Issue by bjorgvin92** [hgop/syllabus-2021#35]
Næ ekki að deploya

Fæ error í kubectl apply

Error from server (BadRequest): error when creating "connect4-server.yaml": Secret in version "v1" cannot be handled as a Secret: v1.Secret.Data: decode base64: illegal base64 data at input byte 12, error found in #10 byte of ...|sessurnar","SECRET_K|..., bigger context ...|","DATABASE_USERNAME":"*************","SECRET_KEY":"********************"},"kind":"Secr|...

Exited with code exit status 1

Veit ekki alveg hvernig ég á að höndla secret.yaml

**Comment by IngaI** [comment]
Við erum að lenda í því sama :/ spurning hvað þarf að vera í base64 og hvað ekki...

**Comment by ironpeak** [comment]
Values í secrets þurfa að vera base64 encoded.

docs: https://kubernetes.io/docs/concepts/configuration/secret/

Það er eini k8s resource-ið sem þarf base64 encoding (af því sem við notum í verkefninu).

**Comment by hauks96** [comment]
> Values í secrets þurfa að vera base64 encoded.
> 
> docs: https://kubernetes.io/docs/concepts/configuration/secret/
> 
> Það er eini k8s resource-ið sem þarf base64 encoding (af því sem við notum í verkefninu).

Við gerðum það en bash scriptan setur gæsalappir utanum base64 strenginn.

**Comment by ironpeak** [comment]
Geturu komið með dæmi?
