### ISSUE TITLE
Cannot start live game

### ISSUE THREAD

**Issue by IngaI** [hgop/syllabus-2021#38]
Should we be able to start a new game by now or should the buttons still be inactive?
![image](https://user-images.githubusercontent.com/54936567/144046011-79e04eca-ede7-45d9-a0c9-dd9f111788eb.png)
![image](https://user-images.githubusercontent.com/54936567/144045734-c88e8d6e-742d-4e60-92df-691a4e643ac4.png)

**Comment by ironpeak** [comment]
What do the server logs say?

**Comment by hauks96** [comment]
We've fixed the URL problem, however the client/server communication still produces many errors, although running locally works

**Comment by ironpeak** [comment]
Playing an entire game won't work, unless you've already implemented the missing connect4-server logic.
