### ISSUE TITLE
yarn test not running

### ISSUE THREAD

**Issue by IngaI** [hgop/syllabus-2021#39]
We had a majorly frustrating issue with running `yarn test` because npm refused to update from version 10.x...

This helped:
https://askubuntu.com/questions/426750/how-can-i-update-my-nodejs-to-the-latest-version

Just in case someone else can use it :)

**Comment by ironpeak** [comment]
What issue were you running into?

**Comment by kthorri** [comment]
Are you using npm?

**Comment by IngaI** [comment]
Yebb and the npm refused to update because for some reason it defaulted to version 10 but 17 was latest 🙄
I was able to fix it... just a headache!
