### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by hauks96** [hgop/syllabus-2021#40]
```
You'll need to make sure you're testing all major states 
that each component can inhibit.
```

What are we supposed to test?

The properties of the react components are not testable with this library, so the states cannot be tested. The only thing we can test is the text rendered into the document by the components, which is not much to go off of.

**Comment by IngaI** [comment]
According to the practical session, he said we should just be component testing the client code... not connected to the server.

**Comment by ironpeak** [comment]
Yes, these are component/unit tests and they should be very low level. 

Unit tests should only care about the unit under, you will get to write acceptance/api/service tests in day 8 and an End 2 End test in week 3 where you test how the client and server integrate together.
