### ISSUE TITLE
Cannot find module 'next/babel'

### ISSUE THREAD

**Issue by robertatli** [hgop/syllabus-2021#41]
When running `yarn test` after the add `App.test.js` step in day-07, step 2 I get the following error

![image](https://user-images.githubusercontent.com/22518971/144089667-e010038e-45c1-43bd-b37c-51c415c75ee4.png)

**Comment by ironpeak** [comment]
The client part in day 7 should be done from within the `./src/connect4-client` directory. It looks like you did it in the root of the repository.
