### ISSUE TITLE
VMware/Ubuntu fer ekki í gang

### ISSUE THREAD

**Issue by elisaeik** [hgop/syllabus-2021#44]
Veit einhver hvað gæti verið vandamálið? VMware loadast bara ekki. Er búin að restarta, slökkva/kveikja og bæta við memory. 

![image](https://user-images.githubusercontent.com/54938207/144127996-8b7477e6-f470-40ec-8b88-7094d3c17f88.png)

**Comment by ironpeak** [comment]
Erfitt að segja hvað gæti verið að :|

Líklega einfaldast að búa bara til nýja VM, ef þú heldur að þetta sé tengt VMWare geturu prófað að nota annað tól eins og VirtualBox, en þetta getur líka gerast við ýmsar sudo aðgerðir þegar fólk er að læra :)
