### ISSUE TITLE
Workflow day08

### ISSUE THREAD

**Issue by bjorgvin92** [hgop/syllabus-2021#47]
Hvernig á workflow-ið að vera? 
nodetests -> pythonunittests -> build -> publish ->  deployacceptanceserver -> acceptancetests -> deploy?

**Comment by ironpeak** [comment]
tests + build má runna á sama tíma, publish á bara að keyra ef tests + build succeeda

**Comment by bjorgvin92** [comment]
Hvar viltu fá deploy acceptance server? Milli node og python? Ef svo er ekki hætta á því að serverinn er ekki sá sami og sá sem mun spítast út úr build jobbinu í þessari keyrslu?

**Comment by ironpeak** [comment]
acceptance test-inn þurfa að keyra eftir publish, því þau þurfa að nota image-ið
