### ISSUE TITLE
Coverage aim

### ISSUE THREAD

**Issue by bjorgvin92** [hgop/syllabus-2021#51]
Erum við að vinna með eitthvað viðmið? Man ekki eftir að hafa séð það í verkefnalýsingu en í einhverjum fyrirlestri var talað um 80%+

**Comment by ironpeak** [comment]
Enginn krafa um neina ákveðna %, ef þið hafið tíma getiði reynt að koma henni í 80+ og tekið það fram í extras sem þið gerðuð fyrir mögulegan bonus.

En byrjið allavega á því að klára alla dagana fyrst.
