### ISSUE TITLE
ReferenceError: fetch is not defined

### ISSUE THREAD

**Issue by jonakaren** [hgop/syllabus-2021#52]
Fáum villuna ReferenceError: fetch is not defined þegar við notum föllin í GameApiClient inn í unit testunum okkar.
<img width="575" alt="Screenshot 2021-12-01 at 20 29 27" src="https://user-images.githubusercontent.com/70695859/144309081-12540f95-8e39-4b04-9cf4-86275608ba12.png">
Erum búin að reyna að yarn adda öllu sem heitir eitthvað fetch en ekkert búið að virka enn.

**Comment by ironpeak** [comment]
ættuð ekki að vera að nota GameApiClient í unit testunum, ef þið þurfið að fylla inn í props fyrir eh component með því getiði notað MockGameClient.
