### ISSUE TITLE
Final exam sample?

### ISSUE THREAD

**Issue by IngaI** [hgop/syllabus-2021#55]
Could we get to see some old final exams so we know what to expect?
I.e. will the questions be essays/multiple choice, are they from the book/lectures or the project?

**Comment by kthorri** [comment]
@stefaneg @hap2000 

?

**Comment by hap2000** [comment]
We will post an example of an exam probably on Saturday and we will also have a Q&A session next week. 
We haven't created the exam yet so I'm not going to confirm what type of question will be this year. 

There are usually no long essays in the exams. 

You should focus on the lectures and use the book to loo up concepts you need more clarity on or deeper understanding. Sometimes we have had 1-2 questions from the lab exercises.
