### ISSUE TITLE
Capacity tests

### ISSUE THREAD

**Issue by bjorgvin92** [hgop/syllabus-2021#56]
![image](https://user-images.githubusercontent.com/42970144/144480641-ab93d62f-2a29-41d9-8566-81277c72f723.png)
Þessar tölur geta ekki verið réttar... er það?
Var búinn að double og triple checka að ég væri alveg 100% að runna á capacity environmentið og það að capacity namespaceið er með 3x pods undir server...
Er ég hugsanlega að gera eitthvað rangt?
Er að runna bæði frá local terminal

**Comment by ironpeak** [comment]
Nei þetta er flott, líklega er þetta að keyra á svipuðum tíma af því að database-inn er bottleneck en ekki server-inn :)
