### ISSUE TITLE
Problem when running pytest

### ISSUE THREAD

**Issue by gautigudmann** [hgop/syllabus-2021#59]
Er að lenda í veseni með að keyra skipunina pytest ./src/tests/unit of fæ þetta:
<img width="1093" alt="Screenshot 2021-12-02 at 18 27 24" src="https://user-images.githubusercontent.com/42963182/144504027-b4a8b0ae-c3e0-49f2-9d03-bd38c36da0e0.png">
Veit einhver hvað þetta gæti verið?

**Comment by Ramruqai** [comment]
Er með sama. Hef ekki komist að niðurstöðu mun pinga hér ef ég finn.

**Comment by ironpeak** [comment]
~~~bash
cd ./src/connect4-server
export PYTHONPATH="./src"
just venv
source .venv/bin/activate
just install
# pytest etc
~~~

**Comment by Ramruqai** [comment]
vantaði að installa öllum requirements.txt hjá mér!
