### ISSUE TITLE
Status code 500 on acceptance test

### ISSUE THREAD

**Issue by bjorgvin16** [hgop/syllabus-2021#60]
Ég er að gera acceptance testið mitt með helpernum sem var gefinn og ég fæ alltaf status code 500 á responsinu sem ég fæ til baka. Er að nota urlið https://connect4-server.acceptance.{{team name}}.hgopteam.com þar sem {{team name}} er team namið okkar. Hefur einhver annar lent í þessu/veit hvað er í gangi?
<img width="370" alt="Screen Shot 2021-12-03 at 10 20 48" src="https://user-images.githubusercontent.com/54938489/144586571-5de603e1-013f-4afa-8c0d-2fa52cac9a5c.png">

**Comment by bjorgvin16** [comment]
test_status testið fær passed

**Comment by Arnarps** [comment]
þetta er að faila á þessu falli er það ekki?

![image](https://user-images.githubusercontent.com/54935919/144593508-0cf01e27-fb1f-4f7b-8ff2-1d8675c37cb0.png)

gæti það verið að þetta sé vandamál með URL_API?

**Comment by bjorgvin16** [comment]
já mögulega en ég gerði print(API_URL) og ég fæ bara þetta url sem er það sem ég nota í skipuninni: https://connect4-server.acceptance.bjona.hgopteam.com

**Comment by bjorgvin16** [comment]
vantaði upp á game logic. það virkaði allt en átti eftir að fara í gegnum pipelineið svo það yrði applyað á kubernetes clusterið
