### ISSUE TITLE
Pytest ekki að virka í circleci

### ISSUE THREAD

**Issue by jonakaren** [hgop/syllabus-2021#61]
EInhver sem hefur fengið þessa villu við að keyra pytestin í circleci? Þau virka öll locally hjá okkur og jobið okkar er alveg eins og í verkefnalýsingunni.

<img width="1121" alt="Screenshot 2021-12-03 at 11 01 01" src="https://user-images.githubusercontent.com/70695859/144591765-100636f7-0430-40f2-a655-e6705e4e221e.png">

**Comment by Arnarps** [comment]
ég er að fá það nákvæmlega sama eins og er

**Comment by Ramruqai** [comment]
Hvernig lítur requirments_dev.txt út hjá ykkur?
Finnst vera svipað og það sem ég var að lenda í þegar ég var ekki með requirements rétt.

Eruði með __init__.py í möppunum sem þið þurftuð að búa til?

**Comment by jonakaren** [comment]
erum búin að setja __init__.py í connect4 möppuna og unit möppuna.
En requirements lítur svona út hjá okkur

<img width="188" alt="Screenshot 2021-12-03 at 12 44 26" src="https://user-images.githubusercontent.com/70695859/144604634-8d63c618-811c-4f14-9a33-7cda6278a3e3.png">

**Comment by hauks96** [comment]
Nenniru að sceenshotta folder structureið í src möppuni?
