### ISSUE TITLE
Outdated link in week2 assignment

### ISSUE THREAD

**Issue by IngaI** [hgop/syllabus-2021#63]
![image](https://user-images.githubusercontent.com/54936567/144641781-1b6ac17e-cd1f-4ada-8e5d-1503e6a487b9.png)
![image](https://user-images.githubusercontent.com/54936567/144641958-05ad8839-a306-470d-8b9b-b4fce7cc0213.png)

**Comment by bjorgvin16** [comment]
Þetta er link á syllabus frá 2020, hægt að breyta því í 2021 og þá kemur þetta

**Comment by IngaI** [comment]
> Þetta er link á syllabus frá 2020, hægt að breyta því í 2021 og þá kemur þetta

Það er frekar augljóst... bara benda kennurum á svo þeir geti lagað eða sett á lista til að laga fyrir næsta ár ;)
