### ISSUE TITLE
Capacity test Assertion error (status code)

### ISSUE THREAD

**Issue by robertatli** [hgop/syllabus-2021#64]
## Acceptance test work, however capacity tests, when set up the same way acceptance tests were fail, as if the API_URL is wrong

![image](https://user-images.githubusercontent.com/22518971/144641828-02c20de1-976d-4ca3-9d00-4d7b07ef9df2.png)
### kubectl commands
Only thing that seems wrong here is the connect4-server for the capacity namespace has its status as `ImagePullBackOff`

![image](https://user-images.githubusercontent.com/22518971/144641581-4b689f3a-5277-4ed5-87a1-0cde88ecd93e.png)
### config.yml creating environments
![image](https://user-images.githubusercontent.com/22518971/144641694-bc16d57a-fed8-404a-aa1d-914951ae4466.png)
### config.yml running tests in environment
![image](https://user-images.githubusercontent.com/22518971/144641945-abf7cff7-33b7-48ee-b125-e15ac118ba8e.png)

**Comment by bjorgvin16** [comment]
Tékkaðu á logs á kubectl server podinu. Það gæti verið að game logicið þitt sé að fokka í þessu. Það var svoleiðis hjá okkur. Við enduðum á því að þurfa að keyra virkandi game logic commit í gegnum alla pípuna (og deploya því) til þess að hætta að fá þetta error. Annars, ef þú ert að búa til acceptance og capacity environment í fyrsta skipti þá þurfa pods smá tíma til að startast, svo ef game logicið þitt er rétt þá gæti þetta error hætt að koma ef þú keyrir pípuna aftur.

**Comment by robertatli** [comment]
## UPDATE

### Þurfti bara að bíða eins og þú sagðir, takk
