### ISSUE TITLE
Week3 assignments still unpublished

### ISSUE THREAD

**Issue by IngaI** [hgop/syllabus-2021#65]
![Screenshot_20211204-135217_GitHub.jpg](https://user-images.githubusercontent.com/54936567/144712044-3454ce86-585b-4777-801f-137f4e7c1cff.jpg)

**Comment by ironpeak** [comment]
We've not finished grading all the assignments, once that's done we'll publish week 3

**Comment by ironpeak** [comment]
Day 11 is out and about.
