### ISSUE TITLE
Datetime typing?

### ISSUE THREAD

**Issue by bjorgvin92** [hgop/syllabus-2021#68]
![image](https://user-images.githubusercontent.com/42970144/144834848-466dc466-e48a-49b6-a441-3bbc6928741d.png)
Hvaða type er eiginlega Datetime?

**Comment by bjorgvin92** [comment]
Eða tökum við þetta aldrei inní init? Semsagt að við gerum bara created = time.Now() í fallið sjalft

**Comment by bjorgvin92** [comment]
æji nvm þetta er default gildið

**Comment by bjorgvin92** [comment]
Það væri kannski gott að vita typingið eftir allt saman fyrir BaseGameResponse init fallið.

**Comment by ironpeak** [comment]
type `datetime` ^^

you need to import it first:
~~~python
from datetime import datetime
~~~
