### ISSUE TITLE
just add_migration "add created field" error

### ISSUE THREAD

**Issue by jonakaren** [hgop/syllabus-2021#69]
Fáum alltaf þessa villu þegar við keyrum just add_migration "add created field", veit einhver hvað er í gangi?

<img width="840" alt="Screenshot 2021-12-06 at 13 16 56" src="https://user-images.githubusercontent.com/70695859/144852677-9480600a-ea0b-47a5-ac5d-e4dd76b49435.png">

**Comment by bjorgvin16** [comment]
fengum hjalp i dæmatima
