### ISSUE TITLE
Day11 status code in initialize_game()

### ISSUE THREAD

**Issue by bjorgvin92** [hgop/syllabus-2021#70]
Erum að reyna keyra acceptance tests
Pípan annars flýgur í gegn nema í helper.initialize_game() þá fer allt í stop í annari línu þá er ætlast til þess að status_code 201 == 500.

**Comment by bjorgvin16** [comment]
https://github.com/hgop/syllabus-2021/issues/60 er þetta sama/svipað vandamál?

**Comment by bjorgvin92** [comment]
Nei ég held að þetta sé ekki það sama. Mér tókst að láta acceptance testin virka í week2

**Comment by Ramruqai** [comment]
Ég er með sama vandamál, ekki alveg að kveikja hvað ég er að gera vitlaust.

**Comment by Ramruqai** [comment]
Vandamálið endaði á að vera að það voru til instances af þessum entities í DB með null sem created (obviously maybe?).

Hrafn breytti verkefnalýsingu til að leyfa null í created field skilst mér.
