### ISSUE TITLE
Should we create separate lock files for requirements and requirements_dev?

### ISSUE THREAD

**Issue by IngaI** [hgop/syllabus-2021#71]
![image](https://user-images.githubusercontent.com/54936567/144862005-e302252f-d01a-43d0-9b6e-bb2c942145b6.png)

**Comment by OliBirgir** [comment]
Sýnist ekki. Ef þú skrollar neðst niður þá sést aðeins einn lock file
<img width="346" alt="Screenshot 2021-12-06 at 16 23 28" src="https://user-images.githubusercontent.com/54917165/144883140-835c8231-57f0-4a6f-a424-708243e2ead7.png">

**Comment by IngaI** [comment]
Úff maður er nú búinn að læra að taka þessu tré ekki of alvarlega >.<

**Comment by bjorgvin16** [comment]
Eruð þið að ná að installa requirements_lock? Fæ alltaf eh error út á þessi blessuðu hashes

**Comment by OliBirgir** [comment]
búinn að gera python -m pip install pip-tools?

**Comment by bjorgvin16** [comment]
jebbs, fæ þetta í server-unit-tests jobbinu
```
ERROR: In --require-hashes mode, all requirements must have their versions pinned with ==
```

**Comment by OliBirgir** [comment]
Hvernig lýtur requirements.txt út hjá þér?

**Comment by ironpeak** [comment]
það er ekki krafa að gera lock file fyrir dev requirements.

Sé að þú ert með `==` í lock filenum, ertu mögulega á ARM64 eða windows etc?

**Comment by ironpeak** [comment]
Ertu inní venv?

**Comment by jonakaren** [comment]
Við Björgvin erum á mac og ekki inní venv.
Requirements.txt lýtur svona út hjá okkur.

<img width="242" alt="Screenshot 2021-12-07 at 00 07 41" src="https://user-images.githubusercontent.com/70695859/144942342-8f2db40f-63af-4455-8a36-e98a0a0485aa.png">

**Comment by jonakaren** [comment]
Fundum út úr þessu, þurftum bæta við `- run: pip install pip==20.2.4` í config jobbið og setja docker imageið í python environmentinu í 3.9 (vorum með 3.8)

**Comment by ironpeak** [comment]
Þið ættuð að vera í venv þegar þið generate-ið lockfile-inn (eða gerið eh python related).
