### ISSUE TITLE
Day11 Part 2

### ISSUE THREAD

**Issue by bjorgvin92** [hgop/syllabus-2021#72]
Ég er með nokkrar spurningar varðandi Part 2.
Vilji þið að við gerum requirements_lock file sem við notum í docker build en notum Dependabot til þess að uppfæra requirements.txt en þar sem við notum það ekki lengur þá er það okkar ákvörðun um hvenær við viljum uppfæra lock file-inn eða á circleCI að sjá um að generate-a nýjan lock file?
Svo varðandi client lock file. Ég er mjög óviss um hvernig það á í raun að virka í zero-install formi væri til í að fá smá hint varðandi það.
Er það að sjá um uppfærslur pakka eina sem þið viljið tengt Dependabot?

**Comment by ironpeak** [comment]
Þið notið requirements.txt enþá til að define-a dependancies sem þið notið directly

Lock file-inn er svo til þess að læsa niður sub dependancies líka.
