### ISSUE TITLE
Yarn lockfile generation

### ISSUE THREAD

**Issue by hauks96** [hgop/syllabus-2021#73]
Can we generate a new lockfile when the dockerfile image is generated?

As of right now we are copying it form the dockerfile, and unable to create a new one with yarn install afterwards, which in turn corrupts the dependabot pipelines.

**Comment by ironpeak** [comment]
You should not apply the dependabot PRs, (this was mostly to show you the security scan integration).

The yarn.lock file should be as it was after week 2.

You shouldn't be using yarn install anywhere in the pipeline (or generating a new lockfile), if you are using yarn install checkout the week 2 solution it does not use yarn install in CI.
