### ISSUE TITLE
cybress not woking when upload to circle

### ISSUE THREAD

**Issue by danielagustbjornsson** [hgop/syllabus-2021#75]
![image](https://user-images.githubusercontent.com/70696534/145023337-d54a0ca2-8cb5-4bb6-aae5-16cf7b800013.png)
this happens if we upload to circle (we added cd to go the the right folder)

**Comment by ironpeak** [comment]
Cypress Issues:
If you are having cypress issues this circleci config worked for me:
  cypress-environment:
    docker:
      - image: cypress/base:16.13.0
...
  e2e-test:
    executor: cypress-environment
    environment:
        PROJECT_DIRECTORY: ./src/connect4-client
    steps:
      - checkout
      - run: cd $PROJECT_DIRECTORY && yarn add -E -D cypress
      - run: cd $PROJECT_DIRECTORY && yarn cypress:headless

It seems cypress is installing some binary on a system that's not being added to .yarn folder 🤔
