### ISSUE TITLE
Yarn binaries not updating?

### ISSUE THREAD

**Issue by hauks96** [hgop/syllabus-2021#77]
All the packages that we have added to our client are added to an "unplugged" folder. 
![image](https://user-images.githubusercontent.com/54936225/145051040-cd68d2dc-c41d-4c47-9d37-ccbbe3fb8d11.png)

We get warnings for "package must be built" even though we tried building locally after adding them.
![image](https://user-images.githubusercontent.com/54936225/145050527-8fd33d30-2dbb-4974-a8c7-d983ccbc2fdc.png)

Some of this we are able to mitigate by running yarn install in the pipeline, but it has been mentioned that it should not be necessary. How can we fix this?

**Comment by ironpeak** [comment]
Cypress Issues:
If you are having cypress issues this circleci config worked for me:
  cypress-environment:
    docker:
      - image: cypress/base:16.13.0
...
  e2e-test:
    executor: cypress-environment
    environment:
        PROJECT_DIRECTORY: ./src/connect4-client
    steps:
      - checkout
      - run: cd $PROJECT_DIRECTORY && yarn add -E -D cypress
      - run: cd $PROJECT_DIRECTORY && yarn cypress:headless

It seems cypress is installing some binary on a system that's not being added to .yarn folder 🤔
